### ISSUE TITLE
Error: You must specify options.format

### ISSUE THREAD

**Issue by brcolow** [Permutatrix/rollup-stream#22]
Hello,

I am upgrading the npm dependencies of a project that I have not touched for a while and am getting the following error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd'
    at error (C:\node_modules\rollup\dist\rollup.js:185:14)
    at checkOutputOptions (C:\node_modules\rollup\dist\rollup.js:10175:3)
    at Object.generate (C:\node_modules\rollup\dist\rollup.js:10237:5)
    at C:\node_modules\rollup-stream\index.js:68:21
```

I am invoking rollup-stream thusly:

```js
gulp.task('scripts', () =>
    rollupStream({
        input: './js/main.js',
        plugins: [
            rollupBabel({
                exclude: ['node_modules/**', 'gulp/**']
            }),
            nodeResolve({ jsnext: true, main: true }),
            commonjs({ include: 'node_modules/**' })
        ],
        sourcemap: true
    }).pipe(source('main.js', '/.js'))
     .pipe(buffer())
// etc.
```

I tried adding the output.format key to the config option but that didn't change anything. I am using the following versions:

```js
    "rollup-plugin-babel": "3.0.2",
    "rollup-plugin-commonjs": "8.2.1",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-stream": "1.24.1",
```

Thanks very much!

**Comment by lemmabit** [comment]
> I tried adding the output.format key to the config option but that didn't change anything.

Could you show me what your gulpfile looked like with this change?

**Comment by brcolow** [comment]
Sure:

```js
gulp.task('scripts', () =>
    rollupStream({
        input: './js/main.js',
        output: {
            format: 'cjs'
        },
        plugins: [
            rollupBabel({
                exclude: ['node_modules/**', 'gulp/**']
            }),
            nodeResolve({ jsnext: true, main: true }),
            commonjs({ include: 'node_modules/**' })
        ],
        sourcemap: true
    }).pipe(source('main.js', '/.js'))
        .pipe(buffer())
       // etc.
```

**Comment by lemmabit** [comment]
rollup-stream interfaces with Rollup's JavaScript API, which doesn't function quite like its config files. I hope to make things more compatible in that respect in a future version. For now, replace `output: { format: 'cjs' }` with a simple `format: 'cjs'`, like this:

```js
gulp.task('scripts', () =>
    rollupStream({
        input: './js/main.js',
        format: 'cjs',
        plugins: [
            rollupBabel({
                exclude: ['node_modules/**', 'gulp/**']
            }),
            nodeResolve({ jsnext: true, main: true }),
            commonjs({ include: 'node_modules/**' })
        ],
        sourcemap: true
    }).pipe(source('main.js', '/.js'))
        .pipe(buffer())
       // etc.
```

**Comment by lemmabit** [comment]
See here for the available options: https://rollupjs.org/#big-list-of-options
